### PR TITLE
Improve and add some pt-BR translations

### PR DESCRIPTION
**Pull request by LeoColman**

### CODE REVIEW

**Comment by eneiluj** [comment]
Hey, thanks for the PR. Translations are actually done in Crowdin: https://crowdin.com/project/moneybuster
They are then automatically processed and inserted in this repo.

**Comment by LeoColman** [comment]
I see. I'll add them there!

**Comment by LeoColman** [comment]
Could you add offline translations to the project? I'd like to upload my files but I don't have permission

**Comment by LeoColman** [comment]
@eneiluj 
Pinging you because I'm not sure if github notifies on a closed PR if you're not mentioned

**Comment by cestmoimeme** [comment]
> @eneiluj Pinging you because I'm not sure if github notifies on a closed PR if you're not mentioned

it works for me, I got an email

**Comment by eneiluj** [comment]
> Could you add offline translations to the project? I'd like to upload my files but I don't have permission

Done

**Comment by LeoColman** [comment]
> it works for me, I got an email
Good to know, won't need to do this again

@eneiluj 
Thanks!
I've just uploaded all the translations and did some more that weren't in the PO file.

Thanks for this amazing project! I'm using it with a group of friends to share our expenses.

**Comment by eneiluj** [comment]
You're welcome. Thanks for your contribution!

**Pull request closed without merging**
