### PR TITLE
Add move bill support

### PR DESCRIPTION
**Pull request by eneiluj**
### Original PR comment:

This is a rough implementation of #87:

- [x] Move basic bill information
- [x] Create payment mode on destination if it doesn't exists already
- [x] Create category on destination if it doesn't exists already
- [x] Try to match who pays and who owe it in the new project

I guess that what's left is:

- [ ] Show the move in the activity manager?
- [ ] Some more permission checks?
- [ ] Write unit tests?
- [ ] Improve design of the "move dialog"?
- [ ] ~~Add translations for all the languages~~ (nothing to be done, strings are sent to Crowdin once it's merged to master)

### New PR comment

@Almamu Let's continue here. 

You can now push to the eneiluj/cospend-nc project in the `Almamu-move-bill-support` branch as you're a member. I pushed your commit plus my adjustments.
* fix eslint warnings/errors (you should see them when you compile, do you?)
* fix bug (my fault) caused by getting the payment mode ID as a string instead of an int
* rename payment method -> payment mode
* add simple style to modal content
* use a computed prop to generate the project list to display (all minus the origin one)

A few thoughts/questions for what's next:
* It would be awesome if you could write some small PhpUnit tests.
* About the activity, we can simply use the existing activities: bill deletion and creation
* The permission check you wrote seems good enough. What more do you think is needed?

> I've taken a quick look at other of your projects and looks like I'll have to write custom CSS for them to look somewhat similar to what nextcloud has, right? I was hoping nextcloud would have predefined ways of styling the modal without custom CSS.

I wouldn't say custom CSS but simply set the style of the content :grin:. Some simple stuff like what I did here is enough.
Each component in `@nextcloud/vue` comes with its style but the modal content is impossible to predict and the developers using the component is free to do anything inside a modal so it's up to them to write it.

### CODE REVIEW

**Comment by Almamu** [comment]
> fix eslint warnings/errors (you should see them when you compile, do you?)

I actually did not see any eslint errors, apart from the ones I fixed, after changing node/npm versions to something closer to what there's in the package.json It looks like I can now properly see all the errors you were mentioning before you fixed them, so I guess that now I should have the right environment setup?

> A few thoughts/questions for what's next:
> 
>     * It would be awesome if you could write some small PhpUnit tests.
> 

👍 

>     * About the activity, we can simply use the existing activities: bill deletion and creation
> 

Okay, I'll implement the activities in the current code then

>     * The permission check you wrote seems good enough. What more do you think is needed?
> 

I have not used any of the sharing features, so I don't know if there's anything else to take into account or if we might want to add some extra checks. For instance, I've just tried the sharing feature, and the UI shows the move/delete buttons, but the "move bill" button is useless when sharing because you can only see one project.

> 
> > I've taken a quick look at other of your projects and looks like I'll have to write custom CSS for them to look somewhat similar to what nextcloud has, right? I was hoping nextcloud would have predefined ways of styling the modal without custom CSS.
> 
> I wouldn't say custom CSS but simply set the style of the content 😁. Some simple stuff like what I did here is enough. Each component in `@nextcloud/vue` comes with its style but the modal content is impossible to predict and the developers using the component is free to do anything inside a modal so it's up to them to write it.

I expected there to be at least some basic components (like title with the right margings, etc) that you could use directly from Nextcloud (just in case they decide to re-design the UI in the future).

**Comment by Almamu** [comment]
That should have fixed the unit tests for all the PHP versions. Looks like ProjectService::getBills returns things ordered differently under certain conditions, as seen in these runs of GitHub actions:
https://github.com/eneiluj/cospend-nc/actions/runs/2812605923
https://github.com/eneiluj/cospend-nc/actions/runs/2812666344

That should be pretty much what was left of the work on the PR. @eneiluj please let me know if you think anything else needs to be done.

**Comment by eneiluj** [comment]
Awesome!

I created some conflicts by bumping the js libs... so the rebase was too painful, I merged master in this branch.
Some additional stuff:
* don't open the move modal if there is no candidate target project
* only show candidate projects in the move modal

The reason I don't hide the move action if there is no candidate project is performance. It would be too costly to check if every bill has a candidate target project so we only check when triggering the move action.

What do you think of all that?
Could you try my changes?
As I merged and did not rebase, you should be able to simply pull this branch.
```
git checkout Almamu-move-bill-support
git pull Almamu-move-bill-support
npm ci ; npm run dev
```

**Comment by Almamu** [comment]
> Some additional stuff:
> 
>     * don't open the move modal if there is no candidate target project
> 
>     * only show candidate projects in the move modal
> 
> 
> The reason I don't hide the move action if there is no candidate project is performance. It would be too costly to check if every bill has a candidate target project so we only check when triggering the move action.

Yeah, that makes sense, it also helps to let the user know that there's a moving functionality if they ever want to use it.

> What do you think of all that?
> Could you try my changes?
> As I merged and did not rebase, you should be able to simply pull this branch.

Changes sound fine to me. I'll give it a try tomorrow, but if everything works fine I guess we could merge it?

**Comment by eneiluj** [comment]
Awesome contribution. Thanks again. Welcome in the authors list :grin:.

**Pull request merged**
