### PR TITLE
Remove error_log of bill day

### PR DESCRIPTION
**Pull request by simonspa**
Signed-off-by: Simon Spannagel <simonspa@kth.se>

### CODE REVIEW

**Comment by simonspa** [comment]
@eneiluj would you mind merging this? I get an email for it from my cron job every day... :rofl:

**Review by eneiluj — APPROVED** [review]

**Comment by simonspa** [comment]
Rebased...

**Comment by eneiluj** [comment]
There was a conflict with master branch. I did it on top of master branch.

**Comment by simonspa** [comment]
Ah, sorry, you were quicker - thanks for fixing!

**Comment by eneiluj** [comment]
:grin:

**Pull request closed without merging**
